#!/bin/zsh
if [[ "$ZSH_THEME" == p10k* ]]; then
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
fi

# Load .zstyles file with customizations.
[[ -r ${ZDOTDIR:-$HOME}/.zstyles ]] && source ${ZDOTDIR:-$HOME}/.zstyles

function autoload-dir {
  local zdir
  local -a zautoloads
  for zdir in $@; do
    [[ -d "$zdir" ]] || continue
    fpath=("$zdir" $fpath)
    zautoloads=($zdir/[^_]*(N:t))
    (( $#zautoloads > 0 )) && autoload -Uz $zautoloads
  done
}

ZFUNCDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/functions"

# Autoload ZFUNCDIR.
if [[ -d "$ZFUNCDIR" ]]; then
  autoload-dir $ZFUNCDIR(N/) $ZFUNCDIR/*(N/)
fi

set_flavor
confded
hybrid_key_bindings

if [[ $ZSH_THEME == p10k ]]; then
  [[ ! -f ${ZDOTDIR:-$HOME}/.p10k.zsh ]] || source ${ZDOTDIR:-$HOME}/.p10k.zsh
elif [[ $ZSH_THEME == starship ]]; then
  eval "$(starship init zsh)"
fi

