#!/bin/zsh
if [[ "$ZSH_THEME" == p10k* ]]; then
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
fi

function autoload-dir {
  local zdir
  local -a zautoloads
  for zdir in $@; do
    [[ -d "$zdir" ]] || continue
    fpath=("$zdir" $fpath)
    zautoloads=($zdir/[^_]*(N:t))
    (( $#zautoloads > 0 )) && autoload -Uz $zautoloads
  done
}

ZFUNCDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/functions"

# Autoload ZFUNCDIR.
if [[ -d "$ZFUNCDIR" ]]; then
  autoload-dir $ZFUNCDIR(N/) $ZFUNCDIR/*(N/)
fi

confded
hybrid_key_bindings

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line -w
  else
    zle push-input -w
    zle clear-screen -w
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

get_secret

if [[ $ZSH_THEME == p10k ]]; then
  [[ ! -f ${ZDOTDIR:-$HOME}/.p10k.zsh ]] || source ${ZDOTDIR:-$HOME}/.p10k.zsh
elif [[ $ZSH_THEME == starship ]]; then
  eval "$(starship init zsh)"
fi

