#!/bin/zsh
#
# .zstyles - zstyle settings for features/plugins that need them.
#

#
# Antidote
#

zstyle ':antidote:bundle' use-friendly-names yes
zstyle ':antidote:plugin:*' defer-options '-p'
zstyle ':antidote:*' zcompile yes

#
# Zephyr features
#

# Use caching.
# zstyle ':zephyr:plugin:*' 'use-cache' yes

#
# Homebrew
#
zstyle ':zephyr:plugin:homebrew' 'keg-only-brews' curl rustup

#
# Confd
#
zstyle ':zephyr:plugin:confd' immediate yes

#
# Completions
#
zstyle ':plugin:ez-compinit' 'compstyle' 'zshzoo'

# Proxy
if [[ "$OSTYPE" == darwin* ]]; then
  zstyle ':plugin:proxy' auto yes
else
  zstyle ':plugin:proxy' mixed "192.168.103.42:7878"
fi
