#!/bin/zsh
#
# .zshenv: Zsh environment file, loaded always.
#

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
mkdir -p $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_STATE_HOME

export EDITOR=nvim
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL=nvim
else
  export VISUAL=zed
fi
export PAGER=less

if [[ "$OSTYPE" == darwin* ]]; then
  # Set browser.
  export BROWSER=${BROWSER:-open}
  # SSH Agent
  export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
fi

# export ZSH_THEME=p10k
export ZSH_THEME=starship

export TERMINFO_DIRS
export XDG_CONFIG_DIRS
export XDG_DATA_DIRS

path=($HOME/.local/bin(N) $path)

