#!/bin/zsh
#
# .zshenv: Zsh environment file, loaded always.
#

export TERMINFO_DIRS
export XDG_CONFIG_DIRS
export XDG_DATA_DIRS
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
mkdir -p $XDG_CONFIG_HOME $XDG_CACHE_HOME $XDG_DATA_HOME $XDG_STATE_HOME

export EDITOR=nvim
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL=nvim
else
  export VISUAL=zed -w
fi
export PAGER=less

zstyle ':plugin:proxy' auto yes

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER=${BROWSER:-open}
elif [[ "$OSTYPE" == linux* ]]; then
  zstyle ':plugin:proxy' mixed "192.168.103.42:7878"
fi

export ZSH_THEME=p10k
# export ZSH_THEME=starship

path=($HOME/.local/bin(N) $path)

zstyle ':plugin:ez-compinit' 'compstyle' 'zshzoo'

