-- return {
--   settings = {
--     texlab = {
--       build = {
--         excutable = "tectonic",
--         args = {
--           "-X",
--           "compile",
--           "%f",
--           "-Z",
--           "shell-escape",
--           "--synctex",
--           "--keep-logs",
--           "--keep-intermediates",
--         },
--         onSave = true,
--         forwardSearchAfter = true,
--       },
--     },
--   },
-- }
