"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	# Navigation
	{ on = "n", run = "leave" },
	{ on = "i", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

	# Goto
	{ on = [
		"g",
		"r",
	], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' },
	{ on = [
		'g',
		'f',
	], run = 'shell -- ya emit cd "$(zoxide query Friends)"' },
	{ on = [
		"g",
		"c",
	], run = "plugin vcs-files" },

	# Plugins
	{ on = "M", run = "plugin mount" },
	{ on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
	{ on = [
		"c",
		"m",
	], run = "plugin chmod", desc = "Chmod on selected files" },
	{ on = [
		"b",
		"a",
	], run = "plugin mactag add", desc = "Tag selected files" },
	{ on = [
		"b",
		"r",
	], run = "plugin mactag remove", desc = "Untag selected files" },
]
