"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"
show_hidden = true
sort_by = "natural"

[preview]
max_width = 1200
max_height = 1200

[input]
cursor_blink = true

[plugin]
prepend_fetchers = [
	{ id = "mime", url = "local://*", run = "mime-ext.local", prio = "high" },
	{ id = "mime", url = "remote://*", run = "mime-ext.remote", prio = "high" },

	{ id = "git", url = "*", run = "git" },
	{ id = "git", url = "*/", run = "git" },

	{ id = "mactag", url = "*", run = "mactag" },
	{ id = "mactag", url = "*/", run = "mactag" },
]

prepend_previewers = [
	{ url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
	{ url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
	{ url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=$XDG_CONFIG_HOME/glamour/themes/catppuccin-$LC_FLAVOR.json "$1"' },
	{ url = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
	{ mime = "application/sqlite3", run = 'piper -- sqlite3 "$1" ".schema --indent"' },
]

append_previewers = [
	{ url = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
]
