"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode = "size"
show_hidden = true
sort_by = "natural"

[preview]
max_width = 1500
max_height = 1500

[input]
cursor_blink = true

[plugin]
prepend_fetchers = [
	{ id = "mime", name = "*", run = "mime-ext", prio = "high" },

	{ id = "git", name = "*", run = "git" },
	{ id = "git", name = "*/", run = "git" },

	{ id = "mactag", name = "*", run = "mactag" },
	{ id = "mactag", name = "*/", run = "mactag" },
]

prepend_previewers = [
	{ name = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
	{ name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
	{ name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
	{ name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
]

append_previewers = [
	{ name = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
]
