[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/conda-zsh-completion"]
    type = "archive"
    url = "https://github.com/conda-incubator/conda-zsh-completion/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/*.tmTheme"]
[".config/btop/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/btop/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/*.theme"]
[".config/lazygit/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/lazygit/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/*/*.yml"]
[".config/spicetify/CustomApps/Marketplace"]
    type = "archive"
    url = "https://github.com/spicetify/spicetify-marketplace/releases/latest/download/spicetify-marketplace.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/spicetify/Themes/marketplace/color.ini"]
    type = "file"
    url = "https://github.com/spicetify/spicetify-marketplace/blob/main/resources/color.ini"
    refreshPeriod = "168h"
[".config/zsh-syntax-highlighting/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["*/*/*.zsh"]
