-- require("minuet").setup {
--   provider = "gemini",
--   provider_options = {
--     openai = {
--       optional = {
--         max_tokens = 256,
--       },
--     },
--     codestral = {
--       optional = {
--         max_tokens = 256,
--         stop = { "\n\n" },
--       },
--     },
--     gemini = {
--       generationConfig = {
--         maxOutputTokens = 256,
--       },
--       safetySettings = {
--         -- HARM_CATEGORY_HATE_SPEECH,
--         -- HARM_CATEGORY_HARASSMENT
--         -- HARM_CATEGORY_SEXUALLY_EXPLICIT
--         category = "HARM_CATEGORY_DANGEROUS_CONTENT",
--         -- BLOCK_NONE
--         threshold = "BLOCK_ONLY_HIGH",
--       },
--     },
--   },
-- }
