packages:
  base:
    shared:
      - "bash"
      - "bat"
      - "bat-extras"
      - "biome"
      - "chafa"
      - "chezmoi"
      - "curl"
      - "direnv"
      - "doppler"
      - "eza"
      - "fd"
      - "fish"
      - "fzf"
      - "gh"
      - "git"
      - "git-delta"
      - "git-flow"
      - "git-lfs"
      # - "gitui"
      - "glow"
      # - "helix"
      - "hexyl"
      - "imagemagick"
      - "jj"
      - "just"
      - "lazygit"
      - "less"
      - "ltex-ls-plus"
      - "lua-language-server"
      - "marksman"
      - "ollama"
      - "rbenv"
      - "ripgrep"
      - "ruff"
      - "rustup"
      - "selene"
      - "shellcheck"
      - "shfmt"
      - "sqlite"
      - "stylua"
      - "taplo"
      # - "television"
      - "texlab"
      - "tmux"
      - "tree-sitter"
      - "uv"
      # - "viu"
      - "vivid"
      - "volta"
      - "wakatime-cli"
      - "wget"
      - "yazi"
      # - "zellij"
      - "zig"
      - "zls"
      - "zoxide"
      - "zsh"
    darwin:
      - "hugo"
      - "laishulu/homebrew/macism"
      - "mas"
      - "hakonharnes/tap/pbctl"
      - "pinentry-mac"
      - "tag"
    linux:
      - "clang"
      - "home-manager"
      - "llvmPackages.openmp"
      - "mihomo"
      - "nix-zsh-completions"
