packages:
  base:
    shared:
      - "alejandra"
      # - "atuin"
      - "bash"
      - "bash-language-server"
      - "bat"
      - "bat-extras"
      - "bear"
      - "biome"
      - "chafa"
      - "chezmoi"
      - "clang-format"
      - "cmake"
      - "codex"
      - "curl"
      - "direnv"
      - "doppler"
      - "eza"
      - "fd"
      - "fish"
      - "fish-lsp"
      - "fzf"
      - "gemini-cli"
      - "gh"
      - "git"
      - "git-delta"
      - "git-lfs"
      # - "gitui"
      - "glow"
      - "grpc"
      # - "helix"
      - "hexyl"
      - "imagemagick"
      - "jj"
      - "just"
      - "lazygit"
      - "less"
      - "ltex-ls-plus"
      - "lua-language-server"
      - "markdown-oxide"
      - "markdownlint-cli2"
      - "marksman"
      - "neocmakelsp"
      - "ollama"
      - "prettierd"
      - "protobuf"
      - "pyrefly"
      # - "rbenv"
      - "ripgrep"
      - "ruby-lsp"
      - "ruff"
      - "rustup"
      - "selene"
      - "shellcheck"
      - "shfmt"
      - "sqlite"
      # - "starship"
      - "stylua"
      - "tailwindcss-language-server"
      - "taplo"
      # - "television"
      - "texlab"
      - "tmux"
      - "tree-sitter-cli"
      - "uv"
      # - "viu"
      - "vivid"
      - "volta"
      - "vscode-langservers-extracted"
      - "vue-language-server"
      - "wakatime-cli"
      - "wget"
      - "yaml-language-server"
      - "yazi"
      # - "zellij"
      - "zig"
      - "zls"
      - "zoxide"
      - "zsh"
    darwin:
      - "hugo"
      - "laishulu/homebrew/macism"
      - "mas"
      - "hakonharnes/tap/pbctl"
      - "pinentry-mac"
      - "tag"
    linux:
      - "clang"
      - "home-manager"
      - "llvmPackages.openmp"
      - "mihomo"
      - "nix-zsh-completions"
    unfree:
      - "claude-code"
