#!/bin/zsh

if (( $# == 0 )); then
	echo >&2 "funcfresh: Expecting function argument."
	return 1
elif ! (( $+functions[$1] )); then
	echo >&2 "funcfresh: Function not found '$1'."
	return 1
fi
unfunction $1
autoload -Uz $1
