#!/bin/zsh

set -a
source <(doppler secrets download --no-file --format env -p dotfiles -c dev_personal 2>/dev/null)
set +a

if [[ "$OSTYPE" == darwin* ]]; then
  export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
fi
