#!/bin/zsh

local config_file="$1"
local pattern="${2:-latte|mocha}"
[[ -z "$LC_FLAVOR" ]] && local LC_FLAVOR="mocha"  # Ensure flavor is set, default to mocha if not
local replacement="${3:-$LC_FLAVOR}"
if [ -f "$config_file" ]; then
	if [[ "$OSTYPE" == darwin* ]]; then
		sed -i '' -E "s/$pattern/$replacement/g" "$config_file"
	else
		sed -i -E "s/$pattern/$replacement/g" "$config_file"
	fi
fi
