#!/usr/bin/env bash

# Use XDG base dirs.
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
mkdir -p "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"

export HISTFILE=$XDG_STATE_HOME/bash/history

export http_proxy="http://192.168.103.42:7878"
export https_proxy="http://192.168.103.42:7878"
export all_proxy="socks5://192.168.103.42:7878"

IA_SHELL=fish

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	NIX_CONFIG_DIR="$XDG_CONFIG_HOME/flake"
	NIX_PROFILE_BIN_DIR="$HOME/.local/state/nix/profile/bin"
	# if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]; then
	if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && $- == *i* ]]; then
		shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
		if [ -f "$NIX_PROFILE_BIN_DIR/$IA_SHELL" ]; then
			exec "$NIX_PROFILE_BIN_DIR/$IA_SHELL" $LOGIN_OPTION
		else
			if command -v nix >/dev/null 2>&1 && [ -d "$NIX_CONFIG_DIR" ]; then
				(cd "$NIX_CONFIG_DIR" && nix run home-manager/master -- switch --flake .#x86_64-linux)
				[ -f "$NIX_PROFILE_BIN_DIR/$IA_SHELL" ] && exec "$NIX_PROFILE_BIN_DIR/$IA_SHELL" $LOGIN_OPTION
			fi
		fi
	fi
fi
