#!/usr/bin/env bash

# Use XDG base dirs.
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
mkdir -p "$XDG_CONFIG_HOME" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$XDG_STATE_HOME"

export HISTFILE=$XDG_STATE_HOME/bash/history

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	NIX_CONFIG_DIR="$XDG_CONFIG_HOME/flake"
	# if [[ $(ps --no-header --pid=$PPID --format=comm) != "zsh" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]; then
	if [[ $(ps --no-header --pid=$PPID --format=comm) != "zsh" && -z ${BASH_EXECUTION_STRING} ]]; then
		shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
		if [ -f "$HOME/.local/state/nix/profile/bin/zsh" ]; then
			exec "$HOME/.local/state/nix/profile/bin/zsh" $LOGIN_OPTION
		else
			if command -v nix >/dev/null 2>&1 && [ -d "$NIX_CONFIG_DIR" ]; then
				(cd "$NIX_CONFIG_DIR" && nix run home-manager/master -- switch --flake .#x86_64-linux)
				[ -f "$HOME/.local/state/nix/profile/bin/zsh" ] && exec "$HOME/.local/state/nix/profile/bin/zsh" $LOGIN_OPTION
			fi
		fi
	fi
fi
